### ISSUE TITLE
Can't find additions, deletions, and changeFiles info from gitlab api.

### ISSUE THREAD

**Issue by jn2657** [SE-8-2021/backend#10]
According to the Github Api Service of PVS, there are three different info: additions, deletions, and changeFiles. However, I can't find the info above from Gitlab Api.

**Comment by jn2657** [comment]
When I use the CommitApi, I get the following information:
{
  "author" : null,
  "authoredDate" : "2021-11-07T06:41:21Z",
  "authorEmail" : "milkkuan@gmail.com",
  "authorName" : "Johnny",
  "committedDate" : "2021-11-07T06:41:21Z",
  "committerEmail" : "milkkuan@gmail.com",
  "committerName" : "Johnny",
  "createdAt" : "2021-11-07T06:41:21Z",
  "id" : "ded46dd1a2266ecd0a65e46e0af164414b2fd2bd",
  "message" : "delete unused code\n",
  "parentIds" : [ "917758c486415e4cf16265fb896f997ff5c9b890" ],
  "shortId" : "ded46dd1",
  "stats" : null,
  "status" : null,
  "timestamp" : null,
  "title" : "delete unused code",
  "url" : null,
  "webUrl" : "https://gitlab.com/jn2657/gitlabapitest/-/commit/ded46dd1a2266ecd0a65e46e0af164414b2fd2bd",
  "lastPipeline" : null
}]

Additions' and Deletions' info should be in "stats", but when i pushed some code, the "stats" was still null.
I don't know how the info actually gets from those files.
In addition, to get the change files' info, the Getdiff function in CommitApi may work.

**Comment by Xanonymous-GitHub** [comment]
Suggest explain this issue in daily meeting.
