### ISSUE TITLE
Add a new porperty to entity but it did not generate getter

### ISSUE THREAD

**Issue by VincentETN** [SE-8-2021/backend#11]
![image](https://user-images.githubusercontent.com/72587013/140873751-6698ff13-4412-4218-96e9-ce294b7578f8.png)

**Comment by VincentETN** [comment]
Solution: Using "Boolean" as the new property type instead of "boolean".
I incidently found that and test built success.

**Comment by Xanonymous-GitHub** [comment]
In Java, `boolean` and `Boolean` are actually different.
`boolean` is a primitive type and `Boolean` is an Object.

So suggest still use `boolean` in that place to save memory usage.

**Comment by VincentETN** [comment]
We cannot call getDeleted() if we use "boolean", you sure?

**Comment by VincentETN** [comment]
Result: If using `boolean` as the type of an entity property, @Getter annotation will generate "is function". However, using `Boolean` will generate "get function" because the annotation may see it as an object.
